name: Build and deploy
on:
    push:
        branches: [master]
    workflow_dispatch:

jobs:
    web-deploy:
        name: 🎉 Deploy
        runs-on: ubuntu-latest
        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v2

            - name: Use Node.js 14
              uses: actions/setup-node@v2
              with:
                node-version: '14'

            - name: 🔨 Build Project
              run: |
                  npm install
                  npm run build

            - name: 📂 Sync files
              uses: SamKirkland/FTP-Deploy-Action@4.1.0
              with:
                  server: ultrapad.finance.server18.arhamsoft.info
                  username: ftp_deploy@ultrapad.finance.server18.arhamsoft.info
                  password: pvLTJi1_^T55
                  protocol: ftps
                  local-dir: build/
                  log-level: verbose
                  dangerous-clean-slate: true
                  